# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

#export EDITOR='vim'

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# via http://stackoverflow.com/a/15157360
alias npm-exec='PATH=$(npm bin):$PATH'
#alias lessc='npm-exec lessc'

alias python='/opt/homebrew/bin/python3.12'

alias clds='claude --model sonnet'
alias cldo='claude --model opus'
alias cld='clds'
alias rc='uv run crewai run'
alias py='uv run pytest'
alias uvvenv='uv venv --python 3.12 && source .venv/bin/activate'
alias uvify='uv venv --python 3.12 && source .venv/bin/activate && uv init --bare && uv add -r requirements.txt'

alias AR='/usr/bin/ar'
alias cls='clear; ls'
alias v='nvim'
alias m='more'
#overrides so I learn shorter aliases above
alias vi='echo "use v!!!"'

alias ll='ls -hlahtr'

alias git lg='nocorrect git lg'
alias ge="git status --porcelain | sed 's/^...//' | xargs -o vim"

# remap default gp alias to use dry-run
alias gp='git push --dry-run'
alias gp!='git push'

alias nrl='npm run eslint:all'
alias nt='npm test'
alias ns='npm start'
alias ntw='npm run test:watch'
alias ntwf='npm run test:watch:firefox'

alias yrl='yarn run lint'
alias yt='yarn test'
alias ys='yarn start'
alias ytw='yarn run test:watch'
alias ytwf='yarn run test:watch:firefox'

alias ytwj='yarn test -- --watch'

#alias bdebuild='curl -sH "Accept-encoding: gzip" https://app.dev.wordsearchbible.com/ | gunzip - | ack "(Build: v\d+)" --output="\$1"'
#alias swchrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/swchrome --ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=https://localhost:8080'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git github jira osx mix frontend-search brew zsh-syntax-highlighting react-native yarn)
plugins=(git github mix frontend-search brew dotenv)

source $ZSH/oh-my-zsh.sh
. `brew --prefix`/etc/profile.d/z.sh
function precmd () {
  _z --add "$(pwd -P)"
}

# Speed up git completion
# via http://stackoverflow.com/questions/9810327/git-tab-autocompletion-is-useless-can-i-turn-it-off-or-optimize-it
__git_files () { 
  _wanted files expl 'local files' _files     
}

#oh-my-zsh git plugin overrides
#alias ls='ls --color=auto'

# If you installed the SDK via Homebrew for React Native
export ANDROID_HOME=/usr/local/opt/android-sdk
#export ANDROID_HOME=/usr/local/Cellar/android-sdk

export FIREFOX_BIN=/Applications/Firefox.app/Contents/MacOS/firefox-bin

# Customize to your needs...
export PATH=:~/bin:/usr/local/bin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin:~/bin
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH


export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home

export PATH=$JAVA_HOME/bin:$PATH

# nvm installed via homebrew
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$PATH"

eval "$(direnv hook zsh)"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Autoload .nvmrc version for nvm
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH
export PATH="$HOME/.fastlane/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Created by `pipx` on 2024-10-26 14:57:27
export PATH="$PATH:/$HOME/.local/bin"

# pnpm
export PNPM_HOME="/Users/kevinold/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export PATH="/opt/homebrew/bin:$PATH"

#function claude() {
#  # Path to your actual claude executable.
#  # Use 'command -v claude' to find the path if you're not sure.
#  /Users/kevinold/.nvm/versions/node/v22.15.1/bin/claude "$@"
#  # Reset the terminal state to clear leftover input.
#  reset
#}

# start starship
eval "$(starship init zsh)"


export PATH="$HOME/.local/bin:$PATH"

# bun completions
[ -s "/Users/kevinold/.bun/_bun" ] && source "/Users/kevinold/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
export PATH="/Users/kevinold/.antigravity/antigravity/bin:$PATH"

eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2024-10-26 14:57:27
export PATH="$PATH:/Users/kevinold/.local/bin"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

# Added by `rbenv init` on Mon Dec 22 07:58:31 CST 2025
eval "$(rbenv init - --no-rehash zsh)"
