# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# via http://stackoverflow.com/a/15157360
alias npm-exec='PATH=$(npm bin):$PATH'
#alias lessc='npm-exec lessc'

alias v='vim'
#overrides so I learn shorter aliases above
alias vi='echo "use v!!!"'

alias ll='ls -hlahtr'
alias ls='ls --color=auto'

alias git lg='nocorrect git lg'
alias ge="git status --porcelain | sed 's/^...//' | xargs -o vim"

# remap default gp alias to use dry-run
alias gp='git push --dry-run'
alias gp!='git push'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github jira osx mix frontend-search brew zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
source ~/bin/z.sh
function precmd () {
  _z --add "$(pwd -P)"
}

# Speed up git completion
# via http://stackoverflow.com/questions/9810327/git-tab-autocompletion-is-useless-can-i-turn-it-off-or-optimize-it
__git_files () { 
  _wanted files expl 'local files' _files     
}

#oh-my-zsh git plugin overrides

# If you installed the SDK via Homebrew for React Native
export ANDROID_HOME=/usr/local/opt/android-sdk

# Customize to your needs...
export PATH=:~/bin:/usr/local/bin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin:~/bin
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

export EDITOR='vim'

export NVM_DIR="/Users/kevinold/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
